version: '3.1'
services:
 drupal: 
  image: drupal:8.2
  ports:
   - "8080:80"
  depends_on:
   - db
  volumes:
   - /var/www/html/modules
   - /var/www/html/profiles
   - /var/www/html/themes
   - /var/www/html/sites
  deploy:
   restart_policy:
    condition: on-failure

 postgres:
  image: postgres:10
  volumes:
   - db_data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER_FILE: /run/secrets/psql_user
   POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
  deploy:
   restart_policy:
    condition: on-failure
  secrets:
   - psql_password
   - psql_user

secrets:
 psql_user:
  external: true
 psql_password:
  external: true
volumes:
  db_data:
